#!/usr/bin/env bash
# Auto-fills the "Activity" section of README.md with one row per repo
# referenced from the Modules tables. Run from the repo root.
#
# Source list = every `https://github.com/networkextension/<repo>` link
# inside README.md (deduped, ordered as they appear).
#
# Per repo: last commit (date + short sha + first-line message) and the
# count of open PRs. Repos the GITHUB_TOKEN cannot see (404) render as
# `private — see repo`.
#
# Requires: gh, jq, awk, sed.
set -euo pipefail

ORG="networkextension"
README="README.md"
BEGIN="<!-- BEGIN:status -->"
END="<!-- END:status -->"

[[ -f "$README" ]] || { echo "README.md not found"; exit 1; }
command -v gh >/dev/null  || { echo "gh required"; exit 1; }
command -v jq >/dev/null  || { echo "jq required"; exit 1; }

# Repos in README order, deduped.
mapfile -t REPOS < <(
  grep -oE "https://github.com/${ORG}/[A-Za-z0-9_.-]+" "$README" \
    | sed "s#https://github.com/${ORG}/##" \
    | awk '!seen[$0]++'
)

if [[ ${#REPOS[@]} -eq 0 ]]; then
  echo "no repos found in README" >&2
  exit 1
fi

# Render the markdown table to a temp file.
tmp=$(mktemp)
{
  echo "$BEGIN"
  echo "<!-- auto-generated by scripts/update-repo-status.sh — do not edit by hand -->"
  echo ""
  echo "_Last refreshed: $(date -u +"%Y-%m-%d %H:%M UTC")_"
  echo ""
  echo "| Repo | Last commit | Open PRs |"
  echo "|---|---|---|"

  for repo in "${REPOS[@]}"; do
    # Repo metadata (404 ⇒ private/inaccessible).
    if ! meta=$(gh api "repos/${ORG}/${repo}" 2>/dev/null); then
      printf "| [\`%s\`](https://github.com/%s/%s) | _private — see repo_ | — |\n" \
        "$repo" "$ORG" "$repo"
      continue
    fi
    default_branch=$(jq -r '.default_branch // "main"' <<<"$meta")

    # Last commit on default branch.
    commit=$(gh api "repos/${ORG}/${repo}/commits/${default_branch}" 2>/dev/null || echo "")
    if [[ -n "$commit" ]]; then
      sha=$(jq -r '.sha[:7]' <<<"$commit")
      date=$(jq -r '.commit.author.date[:10]' <<<"$commit")
      # First line only, escape pipes for markdown table.
      msg=$(jq -r '.commit.message' <<<"$commit" | head -1 | sed 's/|/\\|/g')
      commit_cell=$(printf "%s · [\`%s\`](https://github.com/%s/%s/commit/%s) %s" \
        "$date" "$sha" "$ORG" "$repo" "$sha" "$msg")
    else
      commit_cell="—"
    fi

    # Open PR count.
    pr_count=$(gh api "repos/${ORG}/${repo}/pulls?state=open&per_page=1" \
      --jq 'length' 2>/dev/null || echo "0")
    if [[ "$pr_count" -gt 0 ]]; then
      pr_cell="[$pr_count open](https://github.com/${ORG}/${repo}/pulls)"
    else
      pr_cell="0"
    fi

    printf "| [\`%s\`](https://github.com/%s/%s) | %s | %s |\n" \
      "$repo" "$ORG" "$repo" "$commit_cell" "$pr_cell"
  done

  echo ""
  echo "$END"
} > "$tmp"

# Splice between markers, or append a fresh "Activity" section if missing.
if grep -q "$BEGIN" "$README"; then
  awk -v begin="$BEGIN" -v end="$END" -v block="$tmp" '
    $0 == begin {
      while ((getline line < block) > 0) print line
      skipping = 1
      next
    }
    skipping && $0 == end { skipping = 0; next }
    !skipping { print }
  ' "$README" > "${README}.new"
else
  {
    cat "$README"
    echo ""
    echo "---"
    echo ""
    echo "## Activity"
    echo ""
    cat "$tmp"
  } > "${README}.new"
fi

mv "${README}.new" "$README"
rm -f "$tmp"
echo "README.md updated."
